### PR TITLE
fix: change list color to black

### LINKED ISSUE #30: Sublists still render green
Screen Shot 2020-07-25 at 3 18 08 PM

### PR DESCRIPTION
**Pull request by ningsongshen**
Fixes #30 by changing the font color of classes involving lists. Below is a test to show that it doesn't affect code blocks (or anything else): 
image

However, there are some users that may prefer the colorful list, so this is a design decision.

### CODE REVIEW

**Comment by MorgothSauron** [comment]
Why this is being changed ? The current colors are just fine.

**Comment by mobitar** [comment]
@ningsongshen seems to be some unrelated changes in the dist.js file.

@MorgothSauron the current colors are fine in that we all got used to them, but really, this is a surprise to newcomers. "Why on earth are list elements green?" No where else in the Markdown world does this happen (unless you have examples?)..

**Comment by mobitar** [comment]
@ningsongshen can you also show how it affects code ticks? That is, single tick code boxes rather than triple-tick.

**Comment by ningsongshen** [comment]
The changes in the `dist.js` files seem to appear when I run `grunt`. I only modified the SCSS file, but these still appear, might be the updated compiler? Not sure...

Here are code ticks and preformatted text:

image

**Comment by ningsongshen** [comment]
I think in VSCode the default Markdown rendering uses a yellow/red depending on the theme.

**Pull request merged**
