### PR TITLE
Use gfm Codemirror mode on top of markdown

### PR DESCRIPTION
**Pull request by jonnyparris**
Enables strikethrough formatting as per #11 
Also enables with tasklists and fenced code blocks as a result. However tasklists could probably do with some dedicated css as it seems pretty subtle out of the box

### CODE REVIEW

**Comment by jonnyparris** [comment]
closes #11

**Comment by mobitar** [comment]
Can you give an example Markdown snippet and before/after images of how the text is rendered? Want to make sure we're testing the same thing.

**Comment by jonnyparris** [comment]
Sure thing,
Before:
image
After:
image

No difference to the codeblocks actually, although that wasn't my primary goal here

**Comment by mobitar** [comment]
Looks great, thanks!

**Pull request merged**
